create table contact_main_image (id bigint not null auto_increment, name varchar(255), contact_id bigint, primary key (id)) engine=InnoDB;
create table contacts (id bigint not null auto_increment, created_at datetime(6) not null, email varchar(255), full_name varchar(255), occupation TEXT, phone varchar(255), updated_at datetime(6), contact_main_image_id bigint, primary key (id)) engine=InnoDB;
create table course_teacher (teacher_id bigint not null, version bigint not null, course_id bigint not null, primary key (version, course_id, teacher_id)) engine=InnoDB;
create table course_gallery_image (id bigint not null auto_increment, name varchar(255), course_version bigint, course_id bigint, primary key (id)) engine=InnoDB;
create table course_main_image (id bigint not null auto_increment, name varchar(255), course_version bigint, course_id bigint, primary key (id)) engine=InnoDB;
create table courses (version bigint not null, id bigint not null, course_audience TEXT, course_competency varchar(255), course_document varchar(255), course_field varchar(255), course_form varchar(255), course_goal TEXT, course_price integer, course_start_date date not null, course_status varchar(255), course_study_location varchar(255), course_subject TEXT, course_target_entity varchar(255), course_time integer, course_type varchar(255), created_at datetime(6) not null, created_by varchar(255), eddited_by varchar(255), title TEXT, updated_at datetime(6), url_segment varchar(255), main_image_id bigint, primary key (version, id)) engine=InnoDB;
create table educational_program_stage (id bigint not null auto_increment, description TEXT, title TEXT, course_version bigint, course_id bigint, primary key (id)) engine=InnoDB;
create table index_item (id bigint not null auto_increment, text TEXT, url varchar(255), index_image_id bigint, primary key (id)) engine=InnoDB;
create table index_item_image (id bigint not null auto_increment, name varchar(255), index_item_id bigint, primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, created_at datetime(6) not null, description TEXT, news_status varchar(255), title varchar(255), updated_at datetime(6), url_segment varchar(255), news_main_image_id bigint, primary key (id)) engine=InnoDB;
create table news_main_image (id bigint not null auto_increment, name varchar(255), news_id bigint, primary key (id)) engine=InnoDB;
create table reviews (id bigint not null auto_increment, created_at datetime(6) not null, name varchar(255), text varchar(255), course_version bigint, course_id bigint, primary key (id)) engine=InnoDB;
create table teacher_main_image (id bigint not null auto_increment, name varchar(255), teacher_id bigint, primary key (id)) engine=InnoDB;
create table teachers (id bigint not null auto_increment, created_at datetime(6) not null, full_name varchar(255), teacher_date_of_birth date, teacher_information TEXT, teacher_occupation TEXT, updated_at datetime(6), main_image_id bigint, primary key (id)) engine=InnoDB;
create table user_feedback (id bigint not null auto_increment, course_title varchar(255), created_at datetime(6) not null, email varchar(255), full_name varchar(255), phone varchar(255), question TEXT, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, password varchar(255), role varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table courses add constraint UK_5qn31o6dvecwftx196pq8b7ox unique (url_segment);
alter table news add constraint UK_7hxkxkqwd5aow2fqpaeip4exa unique (url_segment);
alter table contact_main_image add constraint FKktbma1be5gq82uo5j8x0ixfrb foreign key (contact_id) references contacts (id);
alter table contacts add constraint FK342oj91bfj9nbjd5rheo9i8m0 foreign key (contact_main_image_id) references contact_main_image (id);
alter table course_teacher add constraint FKm1dhdu86kr83thi2x4wcarsru foreign key (version, course_id) references courses (version, id);
alter table course_teacher add constraint FKjoytng93eni3erly1divd3xla foreign key (teacher_id) references teachers (id);
alter table course_gallery_image add constraint FKehs8u00034pbvpsf4medu05n5 foreign key (course_version, course_id) references courses (version, id);
alter table course_main_image add constraint FKchw9utwjdp8sqscpnlj0mr8fb foreign key (course_version, course_id) references courses (version, id);
alter table courses add constraint FK8uapq01mham861kykc56yivcf foreign key (main_image_id) references course_main_image (id);
alter table educational_program_stage add constraint FKef06cyql9ej7mb70ma8msvsm9 foreign key (course_version, course_id) references courses (version, id);
alter table index_item add constraint FKpguq7celfnmwg4kyisfgje7cw foreign key (index_image_id) references index_item_image (id);
alter table index_item_image add constraint FKiwxr96pymp6efhm1sfano6go2 foreign key (index_item_id) references index_item (id);
alter table news add constraint FKa4ke93d0kv0qnhcwmansi6ywp foreign key (news_main_image_id) references news_main_image (id);
alter table news_main_image add constraint FKivb8tihh1kxkw6dbosxvr081y foreign key (news_id) references news (id);
alter table reviews add constraint FKpjtnyi89h0457ajfjkb67ll8 foreign key (course_version, course_id) references courses (version, id);
alter table teacher_main_image add constraint FKqor078mmd20vl5dmq7b65f5df foreign key (teacher_id) references teachers (id);
alter table teachers add constraint FKtr4eaws3xqrucf1ecqhc5wq34 foreign key (main_image_id) references teacher_main_image (id);
