package ru.mospolytech.dpo.domain.enumeration;

public enum CourseField {
    WORLDSKILLS_RUSSIA, CHILDREN_TECHNOPARK, INDUSTRY_AND_ECOLOGICAL_SAFETY,
    TRANSPORT, WORK_WITH_SOFTWARE_PRODUCTS, 
    LABOR_PROTECTION_AND_ENERGY_EFFICIENCY, TRANSPORT_OF_DANGEROUS_GOODS, 
    BUILDING, MECHANICAL_ENGINEERING, ECONOMICS_AND_MANAGMENT,
    EDUCATION_AND_PEDAGOGY, LINGUISTICS
}
